CREATE SCHEMA IF NOT EXISTS users;

CREATE TABLE IF NOT EXISTS users.user (
  id BIGSERIAL PRIMARY KEY,
  name VARCHAR(100) NOT NULL,
  cpf VARCHAR(100) NOT NULL,
  address VARCHAR(100),
  email VARCHAR(100) NOT NULL,
  phone VARCHAR(100) NOT NULL,
  created_at TIMESTAMP NOT NULL
);